Page({
  // ["Undecided", "African Studies", "American Studies", "Anthropology", "Art & Art History", "Asian Studies", "Biology", "Chemistry", "Classics", "Computer Science", "Dance", "Earth Sciences", "Economics", "Education", "Engineering", "English", "Environmental Sciences", "Finance", "Gender & Feminist Studies", "History", "International Relations", "Linguistics", "Mathematics", "Medieval & Renaissance Studies", "Music", "Neuroscience", "Philosophy", "Physics", "Political Science", "Psychology", "Public Policy", "Religious Studies", "Sociology", "Statistics", "Urban Studies"],
  data:{
    schoolNum: 0,
    collegedata:[
      {
        names: ["Princeton University", "普林斯顿大学","Princeton", "princeton",  "Princeton university", "princeton university", "普林斯顿",  "普林"],
        path:"../colleges/001/001",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/001.png",
        usnews:1,
        qsus:9,
        tuition:51870,
        tuitionin:0,
        enrollment:5428,
        sat: [[750,800], [710,770]],
        majors: ["Public and International Affairs", "Economics", "History", "Mathematics", "Philosophy", "Computer Science", "Engineering", "Molecular Biology"],
        essay: "2✖️150字短文书 + 1✖️650字长文书 + 一些小问题",
        location:"美国 新泽西州 普林斯顿市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-74.65656,
          latitude:40.34748,
          width:25,
          height:25
        }],
        satCode: 2672,
        toeflCode: 2672
      },{
        names: ["Harvard University","哈佛大学","Harvard", "harvard",  "Harvard university", "harvard university", "哈佛"],
        path:"../colleges/002/002",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/002.png",
        usnews:2,
        qsus:1,
        tuition:51925,
        tuitionin:0,
        enrollment:6788,
        sat: [1460, 1580],
        majors: ["Economics", "Government", "Computer Science", "Applied Mathematics", "History", "Biological Sciences", "East Asian Studies", "African and African American Studies"],
        essay: "2✖️150字短文书 + 1✖️无字数限制长文书 + 1✖️50字微文书",
        location:"美国 马萨诸塞州 剑桥市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-71.11828,
          latitude:42.37088,
          width:25,
          height:25
        }],
        satCode: 3434,
      },{
        names: ["Columbia University", "哥伦比亚大学","Columbia", "columbia",  "Columbia university", "Columbia University in the City of New York", "columbia university", "哥伦比亚", "哥大"],
        path:"../colleges/003/003",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/003.png",
        usnews:3,
        qsus:5,
        tuition:61850,
        tuitionin:0,
        enrollment:6202,
        sat: [1480, 1560],
        majors: ["English", "History", "Political Science", "Economics", "Neuroscience", "Computer Science", "Biology", "Engineering"],
        essay: "5✖️150字列表 + 2✖️300字长文书",
        location:"美国 纽约州 纽约市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-73.96286,
          latitude:40.80783,
          width:25,
          height:25
        }],
        satCode: 2116,
      },{
        names: ["Massachusetts Institute of Technology","麻省理工学院","MIT", "mit",  "麻省理工",  "麻省理工大学", "麻省"],
        path:"../colleges/004/004",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/004.png",
        usnews:3,
        qsus:3,
        tuition:53790,
        tuitionin:0,
        enrollment:4602,
        sat: [[790,800], [730,780]],
        majors: ["Electrical Engineering", "Computer Science", "Mechanical Engineering", "Biology", "Physics", "Aeronautics and Astronautics", "Economics", "Architecture"],
        essay: "2✖️100字短文书 + 3✖️250字长文书",
        location:"美国 马萨诸塞州 剑桥市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-71.09228,
          latitude:42.35906,
          width:25,
          height:25
        }],
        satCode: 3514,

      },{
        names: ["Yale University", "耶鲁大学","Yale", "yale",  "Yale university", "yale university", "耶鲁"],
        path:"../colleges/005/005",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/005.png",
        usnews:3,
        qsus:6,
        tuition:55500,
        tuitionin:0,
        enrollment:5964,
        sat: [[730,790], [720,770]],
        majors: ["Economics", "Life Sciences", "Political Science", "Engineering", "History", "English", "Architecture", "Modern Languages"],
        essay: "1✖️100字短文书 + 1✖️125字短文书 + 4✖️35字微文书 + 2✖️250字长文书",
        location:"美国 康涅狄格州 纽黑文市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-72.96325,
          latitude:41.31134,
          width:25,
          height:25
        }],
        satCode: 3987,
      },{
        names: ["Stanford University", "斯坦福大学","Stanford", "stanford",  "Stanford university", "stanford university", "斯坦福"],
        path:"../colleges/006/006",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/006.png",
        usnews:6,
        qsus:2,
        tuition:53529,
        tuitionin:0,
        enrollment:7087,
        sat: [[740,800],[700,770]],
        majors: ["Computer Science", "Engineering", "Human Biology", "Management Science and Engineering", "Public Policy", "Communication", "Biology"],
        essay: "1✖️150字短文书 + 7✖️50字微文书 + 3✖️250字长文书",
        location:"美国 加利福尼亚州 帕罗奥多市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-122.17022,
          latitude:37.42673,
          width:25,
          height:25
        }],
        satCode: 4704,
      },{
        names: ["University of Chicago", "芝加哥大学","UChicago", "uchicago", "Chicago", "chicago",  "university of chicago", "芝大", "芝加哥"],
        path:"../colleges/007/007",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/007.png",
        usnews:6,
        qsus:12,
        tuition:59298,
        tuitionin:0,
        enrollment:6552,
        sat: [1500, 1560],
        majors: ["Economics", "Natural Sciences", "Mathematics", "Political Science", "English", "Area Studies", "Molecular Engineering", "Pre-med"],
        essay: "2✖️无字数限制长文书",
        location:"美国 伊利诺伊州 芝加哥市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-87.60071,
          latitude:41.79142,
          width:25,
          height:25
        }],
        satCode: 1832,
      },{
        names: ["University of Pennsylvania", "宾夕法尼亚大学","UPenn", "upenn", "Penn", "penn", "Wharton", "wharton",  "university of pennsylvania", "宾大", "沃顿", "沃顿商学院"],
        path:"../colleges/008/008",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/008.png",
        usnews:6,
        qsus:8,
        tuition:57770,
        tuitionin:0,
        enrollment:10183,
        sat: [1460, 1550],
        majors: ["Business", "Engineering", "Nursing", "Finance", "Economics", "Anthropology", "Management and Technology", "Cognitive Science"],
        essay: "1✖️450字长文书 + 1✖️200字短文书",
        location:"美国 宾夕法尼亚州 费城",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-75.19682,
          latitude:39.95003,
          width:25,
          height:25
        }],
        satCode: 2926,
      },{
        names: ["Northwestern University", "西北大学","Northwestern", "northwestern",  "Northwestern university", "northwestern university", "西北"],
        path:"../colleges/009/009",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/009.png",
        usnews:9,
        qsus:16,
        tuition:56691,
        tuitionin:0,
        enrollment:8231,
        sat: [1440, 1550],
        majors: ["Communication", "Economics", "Psychology", "Political Science", "Journalism", "Engineering", "Visual and Performing Arts", "Education", "Pre-med"],
        essay: "1✖️300字长文书",
        location:"美国 伊利诺伊州 埃文斯顿市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-87.67578,
          latitude:42.05698,
          width:25,
          height:25
        }],
        satCode: 1565,
      },{
        names: [ "Duke University", "杜克大学","Duke", "duke", "Duke university", "duke university", "杜克"],
        path:"../colleges/010/010",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/010.png",
        usnews:10,
        qsus:13,
        tuition:58198,
        tuitionin:0,
        enrollment:6682,
        sat: [1500, 1560],
        majors: ["Economics", "Computer Science", "Public Policy", "Biology", "Biomedical Engineering", "Neuroscience", "Global Health", "English"],
        essay: "2(+1)✖️250字长文书",
        location:"美国 北卡罗莱纳州 达勒姆市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-78.93712,
          latitude:36.00203,
          width:25,
          height:25
        }],
        satCode: 5156,
      },{
        names: [ "Johns Hopkins University", "约翰斯霍普金斯大学","JHU", "jhu", "Johns Hopkins", "johns hopkins", "John Hopkins", "john hopkins", "John's Hopkins", "john's hopkins", "John Hopkins University", "John's Hopkins University", "约翰霍普金斯", "约翰霍普金斯大学", "约翰斯霍普金斯"],
        path:"../colleges/011/011",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/011.png",
        usnews:10,
        qsus:14,
        tuition:55350,
        tuitionin:0,
        enrollment:6064,
        sat: [1480, 1550],
        majors: ["Pre-med", "Public Health Studies", "Biomedical Engineering", "Neuroscience", "International Studies", "Engineering", "Creative Writing", "Music"],
        essay: "1✖️400字长文书",
        location:"美国 马里兰州 巴尔的摩市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-76.62103,
          latitude:39.33008,
          width:25,
          height:25
        }],
        satCode: 5332,
      },{
        names: [ "California Institute of Technology", "加州理工学院","CIT", "cit", "Caltech", "caltech", "加州理工", "加州理工大学"],
        path:"../colleges/012/012",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/012.png",
        usnews:12,
        qsus:19,
        tuition:54600,
        tuitionin:0,
        enrollment:948,
        sat: [1530, 1580],
        majors: ["Physics", "Computer Science", "Mechanical Engineering", "Chemistry", "Bioengineering", "Electrical Engineering", "Mathematics", "Geological and Planetar Sciences"],
        essay: "3✖️120字短文书 + 3✖️400字长文书",
        location:"美国 加利福尼亚州 帕萨迪纳市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-118.12451,
          latitude:34.14193,
          width:25,
          height:25
        }],
        satCode: 4034,
      },{
        names: ["Dartmouth College", "达特茅斯学院","Dartmouth University", "Dartmouth", "dartmouth",  "Dartmouth college", "dartmouth college", "Dartmouth university", "dartmouth university", "达特茅斯", "达茅", "达特茅斯大学"],
        path:"../colleges/013/013",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/013.png",
        usnews:12,
        qsus:37,
        tuition:57204,
        tuitionin:0,
        enrollment:4417,
        sat: [[730,790],[710,770]],
        majors: ["Economics", "Government", "Computer Science", "Engineering Sciences", "English", "History", "Biological Sciences", "Foreign Languages"],
        essay: "1✖️100字短文书 + 1✖️300字长文书",
        location:"美国 新罕布什尔州 汉诺佛市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-72.29083,
          latitude:43.70376,
          width:25,
          height:25
        }],
        satCode: 3351,
      },{
        names: ["Brown University", "布朗大学","Brown", "brown",  "Brown university", "brown university", "布朗"],
        path:"../colleges/014/014",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/014.png",
        usnews:14,
        qsus:20,
        tuition:58504,
        tuitionin:0,
        enrollment:7043,
        sat: [1420, 1550],
        majors: ["Economics", "Computer Science", "Applied Mathematics", "Engineering", "Neuroscience", "Classics", "Geology", "Comparative Literature"],
        essay: "1✖️150字短文书 + 3✖️250字长文书",
        location:"美国 罗德岛州 普罗维登斯市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-71.40252,
          latitude:41.82684,
          width:25,
          height:25
        }],
        satCode: 3094,
      },{
        names: ["University of Notre Dame", "圣母大学","Notre Dame", "notre dame",  "university of notre dame", "圣母"],
        path:"../colleges/015/015",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/015.png",
        usnews:15,
        qsus:40,
        tuition:55553,
        tuitionin:0,
        enrollment:8617,
        sat: [1410, 1540],
        majors: ["Economics", "Finance", "Political Science", "Mechanical Engineering", "English", "Theology", "Physics", "Accountancy"],
        essay: "3✖️200字短文书",
        location:"美国 印第安纳州 南本德市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-86.23882,
          latitude:41.70344,
          width:25,
          height:25
        }],
        satCode: 1841,
      },{
        names: ["Vanderbilt University", "范德堡大学", "Vanderbilt", "vanderbilt", "Vanderbilt university", "vanderbilt university", "范德堡"],
        path:"../colleges/016/016",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/016.png",
        usnews:15,
        qsus:30,
        tuition:52070,
        tuitionin:0,
        enrollment:6861,
        sat: [[750,800],[710,760]],
        majors: ["Human and Organizational Development", "Engineering", "Biological Sciences", "Medicine, Health, and Society", "Economics", "Education"],
        essay: "1✖️400字长文书",
        location:"美国 田纳西州 纳什维尔市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-86.80266,
          latitude:36.14485,
          width:25,
          height:25
        }],
        satCode: 1871,
      },{
        names: [ "Cornell University", "康奈尔大学", "Cornell", "cornell","Cornell university", "cornell university", "康奈尔"],
        path:"../colleges/017/017",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/017.png",
        usnews:17,
        qsus:10,
        tuition:57222,
        tuitionin:0,
        enrollment:15182,
        sat: [[720,800],[680,760]],
        majors: ["Engineering", "Business", "Biological Sciences", "Agriculture", "Hotel Administration Architecture", "China and Asia-Pacific Studies", "Industrial and Labor Relations"],
        essay: "1✖️650字长文书",
        location:"美国 纽约州 伊萨卡市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-76.47652,
          latitude:42.44659,
          width:25,
          height:25
        }],
        satCode: 2098,
      },{
        names: ["Rice University", "莱斯大学","Rice", "rice",  "Rice university", "rice university", "莱斯"],
        path:"../colleges/018/018",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/018.png",
        usnews:17,
        qsus:21,
        tuition:49112,
        tuitionin:0,
        enrollment:3992,
        sat: [1470, 1560],
        majors: ["Engineering", "Biosciences", "Social Sciences", "Computer Science", "Architecture", "Economics", "Music", "Entreptreneurship Studies"],
        essay: "2✖️150字短文书 + 1✖️500字长文书 + 1✖️图片",
        location:"美国 德克萨斯州 休斯顿市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-95.40369,
          latitude:29.71594,
          width:25,
          height:25
        }],
        satCode: 6609,
      },{
        names: ["Washington University in St. Louis", "华盛顿圣路易斯大学","华盛顿大学","WUSTL", "wustl", "Washington University in St Louis"],
        path:"../colleges/019/019",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/019.png",
        usnews:19,
        qsus:28,
        tuition:55292,
        tuitionin:0,
        enrollment:7751,
        sat: [1480, 1550],
        majors: ["Business", "Engineering", "Biology", "Social Sciences", "Chemistry", "Biomedical Engineering", "Philosophy-Neuroscience-Pschology", "Pre-med"],
        essay: "1✖️250字长文书",
        location:"美国 密苏里州 圣路易斯市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-90.31066,
          latitude:38.65328,
          width:25,
          height:25
        }],
        satCode: 6929,
      },{
        names: ["University of California, Los Angeles", "加州大学洛杉矶分校", "UCLA", "ucla", "UC Los Angeles", "University of California Los Angeles"],
        path:"../colleges/020/020",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/020.png",
        usnews:20,
        qsus:6,
        tuition:42218,
        tuitionin:13226,
        enrollment:31577,
        sat: [1370, 1540],
        majors: ["Economics", "Sociology", "Biology", "Political Science", "Engineering", "Mathematics", "Chemistry", "Theater"],
        essay: "4✖️350字长文书",
        location:"美国 加利福尼亚州 洛杉矶市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-118.44636,
          latitude:34.07059,
          width:25,
          height:25
        }],
        satCode: 4837,
      },{
        names: ["Emory University", "埃默里大学", "Emory", "emory", "Emory university", "emory university", "埃默里"],
        path:"../colleges/021/021",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/021.png",
        usnews:21,
        qsus:27,
        tuition:53804,
        tuitionin:0,
        enrollment:7086,
        sat: [[710,790],[690,760]],
        majors: ["Business Administration", "Biology", "Economics", "Nursing", "Neuroscience", "Political Science", "English and Creative Writing", "Irish Studies"],
        essay: "2✖️150字短文书",
        location:"美国 佐治亚州 亚特兰大市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-84.32448,
          latitude:33.79192,
          width:25,
          height:25
        }],
        satCode: 5187,
      },{
        names: ["University of California, Berkeley", "加州大学伯克利分校", "UCB", "ucb", "UC Berkeley", "uc berkeley", "UC berkeley", "University of California Berkeley", "伯克利", "伯克利大学"],
        path:"../colleges/022/022",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/022.png",
        usnews:22,
        qsus:4,
        tuition:43176,
        tuitionin:14184,
        enrollment:30853,
        sat: [1350, 1540],
        majors: ["Computer Science", "Engineering", "Architecture", "Economics", "Political Science", "Business", "Sociology", "Mathematics", "Physics"],
        essay: "4✖️350字长文书",
        location:"美国 加利福尼亚州 伯克利市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-122.25946,
          latitude:37.87234,
          width:25,
          height:25
        }],
        satCode: 4833,
      },{
        names: ["University of Southern California", "南加州大学", "USC", "usc", "university of southern california", "南加大", "南加州"],
        path:"../colleges/023/023",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/023.png",
        usnews:22,
        qsus:15,
        tuition:58195,
        tuitionin:0,
        enrollment:19907,
        sat: [[720,800],[690,760]],
        majors: ["Business", "Social Sciences", "Visual and Performing Arts", "Engineering", "Communication", "Cinematic Arts"],
        essay: "2✖️250字长文书 + 一些小问题",
        location:"美国 加利福尼亚州 洛杉矶市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-118.28593,
          latitude:34.02133,
          width:25,
          height:25
        }],
        satCode: 4852,
      },{
        names: ["Georgetown University", "乔治城大学", "Georgetown", "georgetown", "Georgetown university", "georgetown university", "乔治城"],
        path:"../colleges/024/024",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/024.png",
        usnews:24,
        qsus:23,
        tuition:56058,
        tuitionin:0,
        enrollment:7459,
        sat: [1370, 1530],
        majors: ["International Affairs", "Government", "International Politics", "Finance", "Nursing", "Diplomatic History", "International Economics", "Theology"],
        essay: "1✖️250字长文书 + 2✖️400字长文书 + 1✖️无字数限制长文书",
        location:"美国 华盛顿哥伦比亚特区",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-77.07444,
          latitude:38.90754,
          width:25,
          height:25
        }],
        satCode: 5244,
      },{
        names: ["Carnegie Mellon University", "卡耐基梅隆大学", "CMU", "cmu", "Carnegie Mellon", "carnegie mellon", "carnegie mellon university", "卡梅", "卡内基梅隆", "卡耐基梅隆", "卡耐基梅隆大学"],
        path:"../colleges/025/025",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/025.png",
        usnews:25,
        qsus:17,
        tuition:57119,
        tuitionin:0,
        enrollment:6947,
        sat: [1450, 1550],
        majors: ["Computer Science", "Electrical and Computer Engineering", "Mechanical Engineering", "Information Systems", "Drama", "Music", "Design"],
        essay: "3✖️300字长文书",
        location:"美国 宾夕法尼亚州 匹兹堡市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-79.94307,
          latitude:40.44311,
          width:25,
          height:25
        }],
        satCode: 2074,
      },{
        names: ["University of Michigan", "密歇根大学","UMich", "umich", "university of michigan", "Michigan", "michigan", "密西根大学",  "密西根", "密歇根"],
        path:"../colleges/026/026",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/026.png",
        usnews:25,
        qsus:18,
        tuition:51200,
        tuitionin:15558,
        enrollment:30318,
        sat: [[700,790],[680,750]],
        majors: ["Computer Science", "Business Administration", "Psychology", "Economics", "Foreign Languages", "Engineering", "Pharmaceutical Sciences", "Public Health Sciences"],
        essay: "1✖️150字短文书 + 1✖️300字长文书 + 1✖️500字长文书",
        location:"美国 密歇根州 安娜堡市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-83.73243,
          latitude:42.28206,
          width:25,
          height:25
        }],
        satCode: 1839,
      },{
        names: [ "Wake Forest University", "维克森林大学","Wake Forest", "wake forest", "Forest", "wake forest university", "维克森林"],
        path:"../colleges/027/027",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/027.png",
        usnews:27,
        qsus:92,
        tuition:55440,
        tuitionin:0,
        enrollment:5225,
        sat: [1270, 1410],
        majors: ["Finance", "Communication", "Psychology", "Politics and International Affairs", "Business and Enterprise Management", "Biochemistry and Molecular Biology"],
        essay: "5✖️150字短文书 + 2✖️列表 + 1✖️填空题 + 1✖️300字长文书",
        location:"美国 北卡罗莱纳州 温斯顿-塞勒姆市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-80.27669,
          latitude:36.13422,
          width:25,
          height:25
        }],
        satCode: 5885,
      },{
        names: ["University of Virginia", "弗吉尼亚大学","university of virginia", "UV", "Virginia", "virginia", "UVirginia", "uVirginia",  "弗吉尼亚"],
        path:"../colleges/028/028",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/028.png",
        usnews:28,
        qsus:50,
        tuition:50920,
        tuitionin:17891,
        enrollment:16777,
        sat: [[670,780],[670,740]],
        majors: ["Economics", "Commerse", "Biology", "Psychology", "Foreign Affairs", "Sociology", "Life Sciences", "Public Policy"],
        essay: "2✖️250字长文书",
        location:"美国 弗吉尼亚州 夏洛茨维尔市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-78.50782,
          latitude:38.03356,
          width:25,
          height:25
        }],
        satCode: 5820,
      },{
        names: ["Georgia Institute of Technology", "佐治亚理工学院", "GIT", "git", "Georgia Tech", "georgia tech", "Georgia tech", "Gatech", "gatech", "佐治亚理工", "佐治亚理工大学", "乔治亚理工", "乔治亚理工学院", "乔治亚理工大学", "南方MIT"],
        path:"../colleges/029/029",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/029.png",
        usnews:29,
        qsus:32,
        tuition:33794,
        tuitionin:12682,
        enrollment:16049,
        sat: [1400, 1530],
        majors: ["Computer Science", "Industrial Engineering", "Biomedical Engineering", "Aerospace Engineering", "Civil Engineering", "Mechanical Engineering", "Mathematics", "Architecture"],
        essay: "2✖️300字长文书",
        location:"美国 佐治亚州 亚特兰大市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-84.39572,
          latitude:33.77742,
          width:25,
          height:25
        }],
        satCode: 5248,
      },{
        names: [ "New York University", "纽约大学", "NYU", "nyu","new york university", "New York university", "纽大"],
        path:"../colleges/030/030",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/030.png",
        usnews:29,
        qsus:11,
        tuition:53308,
        tuitionin:0,
        enrollment:26733,
        sat: [[670,790],[660,740]],
        majors: ["Business", "Economics", "Nursing", "Theater", "Dance", "Film and Television", "Foreign Languages", "Accounting"],
        essay: "1✖️400字长文书",
        location:"美国 纽约州 纽约市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-73.99736,
          latitude:40.72775,
          width:25,
          height:25
        }],
        satCode: 2562,
      },{
        names: ["Tufts University", "塔夫茨大学", "Tufts", "tufts", "Tufts university", "tufts university", "塔夫茨"],
        path:"../colleges/031/031",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/031.png",
        usnews:29,
        qsus:35,
        tuition:58578,
        tuitionin:0,
        enrollment:5643,
        sat: [[730,790],[700,760]],
        majors: ["International Relations", "Economics", "Biology", "Computer Science", "Engineering", "Classics", "Philosophy", "Child Study and Human Development"],
        essay: "1✖️150字短文书 + 1✖️250字长文书",
        location:"美国 马萨诸塞州 梅德弗德市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-71.12077,
          latitude:42.40772,
          width:25,
          height:25
        }],
        satCode: 3901,
      },{
        names: [ "University of North Carolina, Chapel Hill","北卡罗来纳大学教堂山分校", "UNC", "unc", "University of North Carolina", "university of north carolina", "Chapel Hill", "chapel hill","University of North Carolina Chapel Hill", "北卡教堂山", "北卡", "北卡罗来纳大学",  "北卡罗来纳"],
        path:"../colleges/032/032",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/032.png",
        usnews:29,
        qsus:38,
        tuition:36222,
        tuitionin:9043,
        enrollment:19117,
        sat: [1310, 1480],
        majors: ["Communication and Media Studies", "Chemistry", "Sociology", "English", "Philosophy", "Biology", "Psychology", "Economics"],
        essay: "2✖️250字长文书",
        location:"美国 北卡罗莱纳州 教堂山市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-79.04764,
          latitude:35.9056,
          width:25,
          height:25
        }],
        satCode: 5816,
      },{
        names: ["University of Rochester", "罗切斯特大学", "Rochester", "rochester", "Rochester university", "rochester university", "罗切斯特"],
        path:"../colleges/033/033",
        imagepath:"cloud://college-assitant-h3d1g.636f-college-assitant-h3d1g-1302512797/collegeimages/033.png",
        usnews:29,
        qsus:30,
        tuition:56026,
        tuitionin:0,
        enrollment:6535,
        sat: [1320, 1500],
        majors: ["Psychology", "Financial Economics", "Economics", "Biomedical Engineering", "Business", "Pre-med", "Optics", "Music"],
        essay: "1✖️250字长文书",
        location:"美国 纽约州 罗切斯特市",
        marker:[{
          iconPath:"../../assets/map-icon.jpg",
          longitude:-77.62924,
          latitude:43.12952,
          width:25,
          height:25
        }],
        satCode: 2928,
      }
    ],
  },
  GotoPage:function(e){
    wx.navigateTo({
      url: e.currentTarget.dataset.path,
    })
  },
  Getinput:function(e){
    let keyword = e.detail.value.input;
    for(var index in this.data.collegedata){
      if(this.data.collegedata[index].names.includes(keyword)){
        this.setData({
          schoolNum: index
        })
        break
      }
    }
  },
  goToProfiles: function(e) {
    console.log(e)
    var id = e.currentTarget.dataset.num
    wx.reLaunch({
      url: '../profiles/profiles?num=' + e.currentTarget.dataset.num,
    })
  },
  goToPage: function() {
    wx.showToast({
      title: '开发中...敬请期待！',
      duration: 1000,
      icon: 'none'
    })
  },

  onLoad: function(e) {
    console.log(this.data.collegedata[1].sat[0].length)
  }
})